import type { URI } from "../src/uri";
import { Ok } from "../src/utils";

Ok satisfies URI<"file:///foo/bar">;
Ok satisfies URI<"mailto:user@host?subject=blah">;
Ok satisfies URI<"http://www.yahoo.com">;
Ok satisfies URI<"http://www.yahoo.com/">;
Ok satisfies URI<"http://1.2.3.4/">;
Ok satisfies URI<"http://www.yahoo.com/stuff">;
Ok satisfies URI<"http://www.yahoo.com/stuff/">;
Ok satisfies URI<"http://www.yahoo.com/hello%20world/">;
Ok satisfies URI<"http://www.yahoo.com?name=obi">;
Ok satisfies URI<"http://www.yahoo.com?name=obi+wan&status=jedi">;
Ok satisfies URI<"http://www.yahoo.com?onery">;
Ok satisfies URI<"http://www.yahoo.com#bottom">;
Ok satisfies URI<"http://www.yahoo.com/yelp.html#bottom">;
Ok satisfies URI<"https://www.yahoo.com/">;
Ok satisfies URI<"ftp://www.yahoo.com/">;
Ok satisfies URI<"ftp://www.yahoo.com/hello">;
// Ok satisfies URI<"demo.txt">;
// Ok satisfies URI<"demo/hello.txt">;
// Ok satisfies URI<"demo/hello.txt?query=hello#fragment">;
// Ok satisfies URI<"/cgi-bin/query?query=hello#fragment">;
// Ok satisfies URI<"/demo.txt">;
// Ok satisfies URI<"/hello/demo.txt">;
// Ok satisfies URI<"hello/demo.txt">;
// Ok satisfies URI<"/">;
// Ok satisfies URI<"">;
// Ok satisfies URI<"#">;
// Ok satisfies URI<"#here">;
Ok satisfies URI<"http://www.yahoo.com?name=%00%01">;
Ok satisfies URI<"http://www.yaho%6f.com">;
Ok satisfies URI<"http://www.yahoo.com/hello%00world/">;
Ok satisfies URI<"http://www.yahoo.com/hello+world/">;
Ok satisfies URI<"http://www.yahoo.com?name=obi&">;
Ok satisfies URI<"http://www.yahoo.com?name=obi&type=">;
Ok satisfies URI<"http://www.yahoo.com/yelp.html#">;
// Ok satisfies URI<"//">;
Ok satisfies URI<"http://example.org/aaa/bbb#ccc">;
Ok satisfies URI<"mailto:local@domain.org">;
Ok satisfies URI<"mailto:local@domain.org#frag">;
Ok satisfies URI<"HTTP://EXAMPLE.ORG/AAA/BBB#CCC">;
// Ok satisfies URI<"//example.org/aaa/bbb#ccc">;
// Ok satisfies URI<"/aaa/bbb#ccc">;
// Ok satisfies URI<"bbb#ccc">;
// Ok satisfies URI<"#ccc">;
// Ok satisfies URI<"#">;
// Ok satisfies URI<"A'C">;
Ok satisfies URI<"http://example.org/aaa%2fbbb#ccc">;
Ok satisfies URI<"http://example.org/aaa%2Fbbb#ccc">;
// Ok satisfies URI<"%2F">;
// Ok satisfies URI<"aaa%2Fbbb">;
Ok satisfies URI<"http://example.org:80/aaa/bbb#ccc">;
Ok satisfies URI<"http://example.org:/aaa/bbb#ccc">;
Ok satisfies URI<"http://example.org./aaa/bbb#ccc">;
Ok satisfies URI<"http://example.123./aaa/bbb#ccc">;
Ok satisfies URI<"http://example.org">;
Ok satisfies URI<"http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html">;
Ok satisfies URI<"http://[1080:0:0:0:8:800:200C:417A]/index.html">;
Ok satisfies URI<"http://[3ffe:2a00:100:7031::1]">;
Ok satisfies URI<"http://[1080::8:800:200C:417A]/foo">;
Ok satisfies URI<"http://[::192.9.5.5]/ipng">;
Ok satisfies URI<"http://[::FFFF:129.144.52.38]:80/index.html">;
Ok satisfies URI<"http://[2010:836B:4179::836B:4179]">;
// Ok satisfies URI<"//[2010:836B:4179::836B:4179]">;
Ok satisfies URI<"http://example/Andr&#567;">;
Ok satisfies URI<"file:///C:/DEV/Haskell/lib/HXmlToolbox-3.01/examples/">;
